### ISSUE TITLE
Let's discuss about how to train model to reproduce results

### ISSUE THREAD

**Issue by pp00704831** [TAMU-VITA/DeblurGANv2#52]
Hello everyone,
Does anyone successfully train the release module to achieve the paper results about PSNR 29?
I only used GoPro dataset to train before, and it achieve PSNR 27, so I am now training to use dataset paper used including GoPro, DVD, and NFS.
I am not sure whether after I use these three datasets to train and then I can achieve the paper released performance.
Could anyone show your experiment to me? Thank you very much!
If I successfully achieve the paper performance, I will show the result.

**Comment by ccliangxd** [comment]
i can't get the results(PSNR=29),i train the model and get the results PSNR=27,SSIM = 0.8

**Comment by ccliangxd** [comment]
i use the Gopro_large datasets about 9G

**Comment by pp00704831** [comment]
I think that because GoPro _large has just 2013 pairs for training, and paper used three datasets DVD、NFS、GoPro combined datasets for training, they mentioned that total training pairs are approximate 10000 images.
Because I have no idea about how the combined these three datasets as paper mentioned in 4.1,
I directly use GoPro and NFS datasets to train, the total number of  data is also approximate 10000.
I am training this model as baseline to check that whether model could achieve higher PSNR now, if it works I will show my results for testing.
Looking forward to others experiment for training, Thank you every much!
歡迎其他有正在訓練或已經訓練好的人一起分享，謝謝~

**Comment by ccliangxd** [comment]
> I think that because GoPro _large has just 2013 pairs for training, and paper used three datasets DVD、NFS、GoPro combined datasets for training, they mentioned that total training pairs are approximate 10000 images.
> Because I have no idea about how the combined these three datasets as paper mentioned in 4.1,
> I directly use GoPro and NFS datasets to train, the total number of data is also approximate 10000.
> I am training this model as baseline to check that whether model could achieve higher PSNR now, if it works I will show my results for testing.
> Looking forward to others experiment for training, Thank you every much!
> 歡迎其他有正在訓練或已經訓練好的人一起分享，謝謝~

你能分享一下你的NFS和Gopro数据集的链接吗？作者给出的数据集链接无法下载数据集，非常感谢你

**Comment by Lie-huo** [comment]
hello, when i run the train.py,there is a mistake.How can i solve the problem?

Traceback (most recent call last):
File "train.py", line 179, in 
train, val = map(get_dataloader, datasets)
File "E:\DeblurGANv2\dataset.py", line 133, in from_config
files_a, files_b = map(list, zip(*data))
ValueError: not enough values to unpack (expected 2, got 0)
train and val in config.yaml：
train:
files_a: ./datasets/train/blur/.png
files_b: ./datasets/train/sharp/.png
val:
files_a: ./datasets/test/blur/.png
files_b: ./datasets/test/sharp/.png

**Comment by pp00704831** [comment]
you should some ** in the file direction:
train:
  files_a: ./datasets/my_dataset/train/blur/**/*.png
  files_b: ./datasets/my_dataset/train/sharp/**/*.png
val:
  files_a: ./datasets/my_dataset/test/blur/**/*.png
  files_b: ./datasets/my_dataset/test/sharp/**/*.png

**Comment by pp00704831** [comment]
> hello, when i run the train.py,there is a mistake.How can i solve the problem?
> 
> Traceback (most recent call last):
> File "train.py", line 179, in
> train, val = map(get_dataloader, datasets)
> File "E:\DeblurGANv2\dataset.py", line 133, in from_config
> files_a, files_b = map(list, zip(*data))
> ValueError: not enough values to unpack (expected 2, got 0)
> train and val in config.yaml：
> train:
> files_a: ./datasets/train/blur/.png
> files_b: ./datasets/train/sharp/.png
> val:
> files_a: ./datasets/test/blur/.png
> files_b: ./datasets/test/sharp/.png

You should add some ** in your data direction
![image](https://user-images.githubusercontent.com/57279608/76963013-43e14a80-695b-11ea-8388-6d47b5b78a32.png)

**Comment by pp00704831** [comment]
> > I think that because GoPro _large has just 2013 pairs for training, and paper used three datasets DVD、NFS、GoPro combined datasets for training, they mentioned that total training pairs are approximate 10000 images.
> > Because I have no idea about how the combined these three datasets as paper mentioned in 4.1,
> > I directly use GoPro and NFS datasets to train, the total number of data is also approximate 10000.
> > I am training this model as baseline to check that whether model could achieve higher PSNR now, if it works I will show my results for testing.
> > Looking forward to others experiment for training, Thank you every much!
> > 歡迎其他有正在訓練或已經訓練好的人一起分享，謝謝~
> 
> 你能分享一下你的NFS和Gopro数据集的链接吗？作者给出的数据集链接无法下载数据集，非常感谢你



> > I think that because GoPro _large has just 2013 pairs for training, and paper used three datasets DVD、NFS、GoPro combined datasets for training, they mentioned that total training pairs are approximate 10000 images.
> > Because I have no idea about how the combined these three datasets as paper mentioned in 4.1,
> > I directly use GoPro and NFS datasets to train, the total number of data is also approximate 10000.
> > I am training this model as baseline to check that whether model could achieve higher PSNR now, if it works I will show my results for testing.
> > Looking forward to others experiment for training, Thank you every much!
> > 歡迎其他有正在訓練或已經訓練好的人一起分享，謝謝~
> 
> 你能分享一下你的NFS和Gopro数据集的链接吗？作者给出的数据集链接无法下载数据集，非常感谢你

作者是用google drive連結，不知道是不是因為這個原因? 因為我可以下載 
NFS: https://drive.google.com/file/d/1Ut7qbQOrsTZCUJA_mJLptRMipD8sJzjy/view
DVD: https://drive.google.com/file/d/1bpj9pCcZR_6-AHb5aNnev5lILQbH8GMZ/view
GoPro: https://drive.google.com/file/d/1KStHiZn5TNm2mo3OLZLjnRvd0vVFCI0W/view
但作者的GoPro似乎是比較大有點奇怪，所以我有從原文網頁下載正確的GoPro datasets，但要自己把資料夾整理一下
GoPro: https://drive.google.com/file/d/1H0PIXvJH4c40pk7ou6nAwoxuR4Qh_Sa2/view

**Comment by Lie-huo** [comment]
我用的从原文网页下载的9G的GoPro datasets训练的模型，但是用test_metrics.py测试时，PSNR = 24，SSIM=0.88左右，我看别人的PSNR一般是27左右，我的怎么差的这么多？请问您是用的是9G的GoPro datasets还是作者给的数据集，另外您改网络的参数了吗？还有一个问题，我在测试的时候速度非常慢，用tesla v100也要2.5个小时，您清楚这是怎么回事吗？

**Comment by pp00704831** [comment]
> 我用的从原文网页下载的9G的GoPro datasets训练的模型，但是用test_metrics.py测试时，PSNR = 24，SSIM=0.88左右，我看别人的PSNR一般是27左右，我的怎么差的这么多？请问您是用的是9G的GoPro datasets还是作者给的数据集，另外您改网络的参数了吗？还有一个问题，我在测试的时候速度非常慢，用tesla v100也要2.5个小时，您清楚这是怎么回事吗？

I am also confused about the datasets, but the GoPro datasets author gave on the link is not the same setting of 2103 for training, and 1111 for testing like I mentioned above, but i sill got the results : PSNR=27, SSIM=0.83, I used 'from skimage.measure import compare_ssim' to evaluate ssim, if you use this, your evaluation time will be faster, i also encountered slowly test situation, but i am not sure whether it will cause low ssim.

I also train the code on GoPro + NFS datasets, total images are approximate 10000 images, i got the PSNR = 30 for training, but still got low PSNR= 26  on GroPro testing data, so directly use this setting will cause overfitting problem like paper mentioned.

Thus, I think maybe we need to  split the data like paper did, but it seems like author did not give the code about how to split the datasets, so if anyone directly train the code on GoPro datasets, PSNR result = 26 or 27 is normal.

Does anyone successfully get the PSNR results like paper released, for the retraining network?
Looking forward to everyone show your experience. Thank You. XD

**Comment by 707278645** [comment]
> 我用的从原文网页下载的9G的GoPro datasets训练的模型，但是用test_metrics.py测试时，PSNR = 24，SSIM=0.88左右，我看别人的PSNR一般是27左右，我的怎么差的这么多？请问您是用的是9G的GoPro datasets还是作者给的数据集，另外您改网络的参数了吗？还有一个问题，我在测试的时候速度非常慢，用tesla v100也要2.5个小时，您清楚这是怎么回事吗？
  请问您的测试速度解决了 我也是测试的时候非常慢 2个小时左右  请问推理效率就是指这个吗 60ms  差的很多啊

**Comment by WongJianyang** [comment]
> 你好，当我运行train.py时，出现了一个错误。我该如何解决该问题？
> 
> 追溯（最近一次通话最近）： 火车中的
> 文件“ train.py”，行179，
> val = map（get_dataloader，数据集），
> 文件“ E：\ DeblurGANv2 \ dataset.py”，行133，位于from_config
> files_a，files_b = map（list，zip（* data））
> ValueError：没有足够的值要解压（预期2，得到0）
> config.yaml中的train和val：
> train： files_a：./ datasets/ train/
> blur/.png
> files_b：./数据集/火车/锐利/ .PNG
> VAL：
> files_a：./datasets/test/blur/.png
> files_b：./datasets/test/sharp/.png
你好，我现在也遇到了这个问题，请问一下你最后是怎么解决的？

**Comment by 707278645** [comment]
GitHub上已经有人回复了 路径要按照自己电脑保存的路径放好就行了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wangjianyang"<notifications@github.com&gt;; 
发送时间: 2020年9月9日(星期三) 下午4:45
收件人: "VITA-Group/DeblurGANv2"<DeblurGANv2@noreply.github.com&gt;; 
抄送: "JF"<707278645@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [VITA-Group/DeblurGANv2] Let&#39;s discuss about how to train model to reproduce results (#52)





  
你好，当我运行train.py时，出现了一个错误。我该如何解决该问题？
 
追溯（最近一次通话最近）： 火车中的
 文件“ train.py”，行179，
 val = map（get_dataloader，数据集），
 文件“ E：\ DeblurGANv2 \ dataset.py”，行133，位于from_config
 files_a，files_b = map（list，zip（* data））
 ValueError：没有足够的值要解压（预期2，得到0）
 config.yaml中的train和val：
 train： files_a：./ datasets/ train/
 blur/.png
 files_b：./数据集/火车/锐利/ .PNG
 VAL：
 files_a：./datasets/test/blur/.png
 files_b：./datasets/test/sharp/.png
 你好，我现在也遇到了这个问题，请问一下你最后是怎么解决的？

**Comment by WongJianyang** [comment]
> GitHub上已经有人回复了路径要按照自己的计算机保存的路径放好就行了
> […](#)
> ------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：“ Wangjianyang” < notifications@github.com> ;; 发送时间：2020年9月9日（星期三）下午4:45收件人：“ VITA-Group / DeblurGANv2” <DeblurGANv2@noreply.github.com> ;；抄送：“ JF” <707278645@qq.com> ;; “评论” <comment@noreply.github.com> ;; 主题：回复：[VITA-组/ DeblurGANv2]让＆[＃39](https://github.com/VITA-Group/DeblurGANv2/issues/39) ; S如何培养模型来再现结果讨论（[＃52](https://github.com/VITA-Group/DeblurGANv2/issues/52)）你好，当我运行train.py时，出现了一个错误。我该如何解决该问题？转向（最近一次通话最近）：火车中的文件“ train.py”，行179，val = map（get_dataloader） ，数据集），文件“ E：\ DeblurGANv2 \ dataset.py”，行133，位于from_config files_a，files_b = map（list，zip（* data））ValueError：没有足够的值要解压（预期2，得到0 ）config.yaml中的train和val：火车：files_a：./ datasets / train / blur / .png files_b：./数据集/ Train /锐利/ .PNG VAL：files_a：./ datasets / test / blur /。 png files_b：./ datasets / test / sharp / .png你好，我现在也遇到了这个问题，请问一下你最后是怎么解决的？？直接回复此电子邮件，在GitHub上查看或取消订阅。
我i没有看懂，是需要更改配置文件代码里面的路径吗？
womeiyoukan

**Comment by 707278645** [comment]
对的把那些路径删了改成自己下载好数据集的路径就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wangjianyang"<notifications@github.com&gt;; 
发送时间: 2020年9月9日(星期三) 下午5:00
收件人: "VITA-Group/DeblurGANv2"<DeblurGANv2@noreply.github.com&gt;; 
抄送: "JF"<707278645@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [VITA-Group/DeblurGANv2] Let&#39;s discuss about how to train model to reproduce results (#52)





  
GitHub上已经有人回复了路径要按照自己的计算机保存的路径放好就行了
 …
 ------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：“ Wangjianyang” < notifications@github.com&gt; ;; 发送时间：2020年9月9日（星期三）下午4:45收件人：“ VITA-Group / DeblurGANv2” DeblurGANv2@noreply.github.com ;；抄送：“ JF” 707278645@qq.com ;; “评论” comment@noreply.github.com ;; 主题：回复：[VITA-组/ DeblurGANv2]让＆＃39 ; S如何培养模型来再现结果讨论（＃52）你好，当我运行train.py时，出现了一个错误。我该如何解决该问题？转向（最近一次通话最近）：火车中的文件“ train.py”，行179，val = map（get_dataloader） ，数据集），文件“ E：\ DeblurGANv2 \ dataset.py”，行133，位于from_config files_a，files_b = map（list，zip（* data））ValueError：没有足够的值要解压（预期2，得到0 ）config.yaml中的train和val：火车：files_a：./ datasets / train / blur / .png files_b：./数据集/ Train /锐利/ .PNG VAL：files_a：./ datasets / test / blur /。 png files_b：./ datasets / test / sharp / .png你好，我现在也遇到了这个问题，请问一下你最后是怎么解决的？？直接回复此电子邮件，在GitHub上查看或取消订阅。
 我i没有看懂，是需要更改配置文件代码里面的路径吗？
 womeiyoukan

**Comment by WongJianyang** [comment]
> 对的把那些路径删除了改成自己下载好数据集的路径就行了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wangjianyang"<notifications@github.com&gt;; 发送时间: 2020年9月9日(星期三) 下午5:00 收件人: "VITA-Group/DeblurGANv2"<DeblurGANv2@noreply.github.com&gt;; 抄送: "JF"<707278645@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [VITA-Group/DeblurGANv2] Let&#39;s discuss about how to train model to reproduce results (#52) GitHub上已经有人回复了路径要按照自己的计算机保存的路径放好就行了 … ------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：“ Wangjianyang” < notifications@github.com&gt; ;; 发送时间：2020年9月9日（星期三）下午4:45收件人：“ VITA-Group / DeblurGANv2” DeblurGANv2@noreply.github.com ;；抄送：“ JF” 707278645@qq.com ;; “评论” comment@noreply.github.com ;; 主题：回复：[VITA-组/ DeblurGANv2]让＆＃39 ; S如何培养模型来再现结果讨论（＃52）你好，当我运行train.py时，出现了一个错误。我该如何解决该问题？转向（最近一次通话最近）：火车中的文件“ train.py”，行179，val = map（get_dataloader） ，数据集），文件“ E：\ DeblurGANv2 \ dataset.py”，行133，位于from_config files_a，files_b = map（list，zip（* data））ValueError：没有足够的值要解压（预期2，得到0 ）config.yaml中的train和val：火车：files_a：./ datasets / train / blur / .png files_b：./数据集/ Train /锐利/ .PNG VAL：files_a：./ datasets / test / blur /。 png files_b：./ datasets / test / sharp / .png你好，我现在也遇到了这个问题，请问一下你最后是怎么解决的？？直接回复此电子邮件，在GitHub上查看或取消订阅。 我i没有看懂，是需要更改配置文件代码里面的路径吗？ womeiyoukan — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，我现在还有一些疑问，你能否加一下我的微信Re01013，我咨询一下。

**Comment by longint1024** [comment]
您好，请问您训练好了吗？我准备把这个model迁移到另一个场景，但我遇到的问题和你一样。在Gopro数据集上我的结果是psnr=27&ssim=0.81，实在是上不去了，很困惑。最关键的是Loss的下降非常奇怪

**Comment by longint1024** [comment]
> i can't get the results(PSNR=29),i train the model and get the results PSNR=27,SSIM = 0.8

me too, have you solved the problem?

**Comment by ccliangxd** [comment]
> > i can't get the results(PSNR=29),i train the model and get the results PSNR=27,SSIM = 0.8
> 
> me too, have you solved the problem?

Perhaps it is because the author mentioned in the paper that they use the NFS, GOPRO, and DVD joint data set. I tried training on the other two data sets separately, and the PSNR and SSIM tested will be higher than those of GOPRO.

**Comment by ldlshizhu** [comment]
> > 我用的从分析师网页下载的9G的GoPro数据集训练的模型，但是用test_metrics.py测试，PSNR = 24，SSIM = 0.88左右，我看别人的PSNR一般是27左右，我的怎么差的这么多？请问您是用的是9G的GoPro数据集还是作者给的数据集，另外您改网络的参数了吗？还有一个问题，我在测试的时候速度非常慢，用tesla v100也要2.5个小时，您清楚这是怎么回事吗？
> 
> 我也对数据集感到困惑，但是作者在链接上给出的GoPro数据集设置与上面提到的2103用于训练，1111用于测试的设置不同，但我仍然得到了结果：PSNR = 27，SSIM = 0.83 ，我使用了'from skimage.measure import compare_ssim'来评估ssim，如果使用它，您的评估时间会更快，我也遇到了缓慢的测试情况，但是我不确定这是否会导致ssim降低。
> 
> 我还在GoPro + NFS数据集上训练了代码，总图像约为10000张图像，我得到了PSNR = 30进行训练，但在GroPro测试数据上仍然得到了低PSNR = 26，因此直接使用此设置将导致像纸张那样的过拟合问题提到。
> 
> 因此，我认为也许我们需要像纸上一样拆分数据，但是似乎作者并没有给出如何拆分数据集的代码，因此，如果有人直接在GoPro数据集上训练代码，则PSNR结果= 26或27为正常。
> 
> 是否有人成功地获得了针对再培训网络的PSNR结果（如论文发布）？
> 期待大家展示您的经验。谢谢。XD

Hello, thank you for your contribution. I saw that you said that you can only use GOPRO for training, right? When you train with GROPRO and NFS, do you need to download NFS with extracted video frames as pictures? My English is poor, thank you again
