### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by Lie-huo** [TAMU-VITA/DeblurGANv2#53]
hello, when i run the train.py,there is a mistake.How can i solve the problem?
I0318 16:56:19.757143 8820 dataset.py:28] Subsampling buckets from 0 to 90.0, total buckets number is 100
I0318 16:56:19.757143 8820 dataset.py:71] Dataset has been created with 18 samples
I0318 16:56:19.762583 8820 dataset.py:28] Subsampling buckets from 90.0 to 100, total buckets number is 100
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    train, val = map(get_dataloader, datasets)
  File "E:\DeblurGANv2\dataset.py", line 133, in from_config
    files_a, files_b = map(list, zip(*data))
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by Sandbox3aster** [comment]
How did you arrange you data? Did you make sure folder ./datasets/train/blur/ &  ./datasets/train/sharp/,  ./datasets/test/blur/ &  ./datasets/test/sharp/ has the same amount of images?

**Comment by Sid-XXD** [comment]
> hello, when i run the train.py,there is a mistake.How can i solve the problem? I0318 16:56:19.757143 8820 dataset.py:28] Subsampling buckets from 0 to 90.0, total buckets number is 100 I0318 16:56:19.757143 8820 dataset.py:71] Dataset has been created with 18 samples I0318 16:56:19.762583 8820 dataset.py:28] Subsampling buckets from 90.0 to 100, total buckets number is 100 Traceback (most recent call last): File "train.py", line 179, in train, val = map(get_dataloader, datasets) File "E:\DeblurGANv2\dataset.py", line 133, in from_config files_a, files_b = map(list, zip(*data)) ValueError: not enough values to unpack (expected 2, got 0)
> 
> and train: files_a: ./datasets/train/blur/_.png files_b: ./datasets/train/sharp/_.png val: files_a: ./datasets/test/blur/_.png files_b: ./datasets/test/sharp/_.png



hi, I also meet this error.
''ValueError: not enough values to unpack (expected 2, got 0)''
Have you solve this error?
thanks

**Comment by MelodeLi** [comment]
hello, when i run the train.py,there is a mistake.
I0927 12:52:07.228861 10180 dataset.py:28] Subsampling buckets from 0 to 90.0, total buckets number is 100
I0927 12:52:07.233865 10180 dataset.py:71] Dataset has been created with 1892 samples
I0927 12:52:07.259889 10180 dataset.py:28] Subsampling buckets from 90.0 to 100, total buckets number is 100
I0927 12:52:07.262892 10180 dataset.py:71] Dataset has been created with 211 samples
Epoch 0, lr 0.01:   0%|          | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:/lxh/DeblurGANv2-master/train.py", line 194, in <module>
    Fire(main)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:/lxh/DeblurGANv2-master/train.py", line 190, in main
    trainer.train()
  File "D:/lxh/DeblurGANv2-master/train.py", line 41, in train
    self._run_epoch(epoch)
  File "D:/lxh/DeblurGANv2-master/train.py", line 66, in _run_epoch
    for data in tq:
  File "E:\anaconda3\envs\pytorch\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\lxh\DeblurGANv2-master\dataset.py", line 111, in __getitem__
    a, b = self.transform_fn(a, b)
  File "D:\lxh\DeblurGANv2-master\aug.py", line 26, in process
    return r['image'], r['sharp']
KeyError: 'sharp'
