### ISSUE TITLE
Which variable cause the torch.FloatTensor/torch.cuda.FloatTensor error?

### ISSUE THREAD

**Issue by Xingyb14** [TAMU-VITA/DeblurGANv2#8]
Have anyone met and solved this error?

Traceback (most recent call last):
  File "DeblurGANv2/train.py", line 189, in <module>
    trainer.train()
  File "DeblurGANv2/train.py", line 45, in train
    self._run_epoch(epoch)
  File "DeblurGANv2/train.py", line 75, in _run_epoch
    loss_content = self.criterionG(outputs, targets)
  File "/home/work/user-job-dir/DeblurGANv2/models/losses.py", line 64, in \_\_call\_\_
    return self.get_loss(fakeIm, realIm)
  File "/home/work/user-job-dir/DeblurGANv2/models/losses.py", line 55, in get_loss
    fakeIm[0, :, :, :] = self.transform(fakeIm[0, :, :, :])
  File "/home/work/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in \_\_call\_\_
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/work/anaconda3/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

**Comment by Xingyb14** [comment]
I wrote my own normalize function to replace transform.Normalize. It works but I did not figure out why this erro occured.

**Comment by Xingyb14** [comment]
@xiaozhi2015 I wrote my own normalize function to replace transform.Normalize. It works but I did not figure out why this erro occured.
